### PR TITLE
Wip/hughsie/gtk4

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Review by GeorgesStavracas — APPROVED** [review]
I would say that a separate package is an overkill - colord-gtk is reasonably small and the API is exactly equal for GTK3 and GTK4. I think it's fine to ship all libraries generated by this project in a single package.

I'm not fluent in .spec files, but the changes here make sense to me.

**Comment by hughsie** [comment]
> I think it's fine to ship all libraries generated by this project in a single package

This means the package will hard depend on gtk3 *and* gtk4 -- is that what we want? It's probably fine for GNOME.

**Comment by A6GibKm** [comment]
Hello, would it be possible to have this for GNOME 43?, feature freeze is around the corner. Thanks!

**Comment by hughsie** [comment]
@A6GibKm it's already in the last release, this is downstream-ish spec file stuff.

**Comment by A6GibKm** [comment]
Thanks for the clarification. Ill mark this done in the dark mode intiiative¹ :)

¹: https://gitlab.gnome.org/GNOME/Initiatives/-/issues/32

**Pull request merged**
